### ISSUE TITLE
Create frontend for displaying temp & pH data 

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/prawnalith#36]
Create a simple frontend display for temp & pH data which can be accessed via Firebase.

- [x] Use firebase auth (See #43)
- [x] Look into using [https://github.com/DenisKolodin/yew](https://github.com/DenisKolodin/yew)  (See #40)
- [x] Use [https://purecss.io/](https://purecss.io/)  (See #43)
- [x] frontend fetches from pond service every N millis (See #54)
- [x] pond service provides tank data (See #45) 

## js interop inspiration 

- js callback https://github.com/DenisKolodin/yew/blob/master/examples/js_callback/static/get-payload-script.js
- importing a js lib from Web https://github.com/DenisKolodin/yew/blob/master/examples/npm_and_rest/src/ccxt.rs

## fetch every N Millis in yew

- https://github.com/DenisKolodin/yew/blob/master/examples/timer/src/lib.rs
- https://github.com/DenisKolodin/yew/blob/master/src/services/fetch.rs
