### ISSUE TITLE
♨️💧 Add digital temp and humidity sensor 💧♨️

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/prawnalith#84]
- [x] Collect data from a DHT11 which measures humidity and temp in a room. 
- [x] Organize it into Redis.
- [x] Push to LED.
- [ ] simplify data model (#90) 
- [ ] Update redis_aggregator (#90) 
- [ ] Make it visible in frontend (#90)
